# Generated by Django 5.0 on 2023-12-06 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100)),
                ('pais', models.CharField(default='Colombia', max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('barrio', models.CharField(blank=True, max_length=100, null=True)),
                ('detalles_adicionales', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=100)),
                ('tel', models.IntegerField()),
                ('fecha_nac', models.DateField()),
                ('tipo_doc', models.TextField()),
                ('num_doc', models.IntegerField()),
                ('correo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('tamano', models.CharField(max_length=100)),
                ('preciobase', models.IntegerField()),
                ('cupo', models.IntegerField()),
                ('servicios_base', models.TextField()),
                ('servicios_ad', models.TextField()),
                ('num_banos', models.IntegerField()),
                ('petfriendly', models.BooleanField()),
                ('direccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.direccion')),
                ('arrendador', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('inmueble', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.inmueble')),
            ],
        ),
        migrations.CreateModel(
            name='Arriendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.inmueble')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.usuario')),
            ],
        ),
    ]
