# Generated by Django 5.0 on 2023-12-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_direccion_barrio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='barrio',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='detalles_adicionales',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='servicios_ad',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='servicios_base',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
