# Generated by Django 5.0 on 2023-12-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_direccion_barrio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='num_doc',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tel',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_doc',
            field=models.CharField(max_length=15),
        ),
    ]
